/**
 * Prints supabase/seed.sql from the same mock data the apps use without Supabase.
 * Usage (from repo root): npm run db:seed-sql
 * Dates are written relative to now() so the dashboard looks fresh whenever you seed.
 */
import { categories, customerSeeds, orderSeeds, productSeeds, unsplash } from "../src/mock/index.ts";

const q = (v: string | null | undefined) => (v === null || v === undefined ? "null" : `'${v.replace(/'/g, "''")}'`);
const arr = (list: string[]) => `array[${list.map(q).join(", ")}]::text[]`;
const ago = (unit: "days" | "minutes", n: number) => `now() - interval '${n} ${unit}'`;

const out: string[] = [];
out.push("-- Generated by packages/db/scripts/generate-seed.ts — do not edit by hand.");
out.push("begin;");
out.push("truncate public.order_items, public.orders, public.customers, public.products, public.categories restart identity cascade;");
out.push("");

out.push("insert into public.categories (id, name, slug, image_url, sort_order) values");
out.push(categories.map((c) => `  (${q(c.id)}, ${q(c.name)}, ${q(c.slug)}, ${q(c.imageUrl)}, ${c.sortOrder})`).join(",\n") + ";");
out.push("");

out.push("insert into public.products (id, name, slug, description, price, compare_at_price, category_id, images, stock, rating, review_count, is_trending, is_active, created_at) values");
out.push(
  productSeeds
    .map((p) => {
      const categoryId = categories[p.cat - 1]!.id;
      return `  (${q(p.id)}, ${q(p.name)}, ${q(p.slug)}, ${q(p.blurb)}, ${p.price}, ${p.compareAt ?? "null"}, ${q(categoryId)}, ${arr(p.photos.map((x) => unsplash(x)))}, ${p.stock}, ${p.rating}, ${p.reviews}, ${Boolean(p.trending)}, true, ${ago("days", p.daysAgo)})`;
    })
    .join(",\n") + ";",
);
out.push("");

out.push("insert into public.customers (id, name, email, phone, city, created_at) values");
out.push(customerSeeds.map((c) => `  (${q(c.id)}, ${q(c.name)}, ${q(c.email)}, ${q(c.phone)}, ${q(c.city)}, ${ago("days", c.daysAgo)})`).join(",\n") + ";");
out.push("");

out.push("insert into public.orders (id, order_number, customer_id, customer_name, email, phone, address, city, status, subtotal, shipping, total, created_at) values");
out.push(
  orderSeeds
    .map((o) => `  (${q(o.id)}, ${q(o.orderNumber)}, ${q(o.customerId)}, ${q(o.customerName)}, ${q(o.email)}, ${q(o.phone)}, ${q(o.address)}, ${q(o.city)}, ${q(o.status)}, ${o.subtotal}, ${o.shipping}, ${o.total}, ${ago("minutes", o.minutesAgo)})`)
    .join(",\n") + ";",
);
out.push("");

out.push("insert into public.order_items (id, order_id, product_id, product_name, image_url, unit_price, quantity) values");
out.push(
  orderSeeds
    .flatMap((o) => o.items)
    .map((i) => `  (${q(i.id)}, ${q(i.orderId)}, ${q(i.productId)}, ${q(i.productName)}, ${q(i.imageUrl)}, ${i.unitPrice}, ${i.quantity})`)
    .join(",\n") + ";",
);
out.push("");
out.push("select setval('public.order_number_seq', (select max(substring(order_number from 4)::int) from public.orders));");
out.push("commit;");

console.log(out.join("\n"));
